apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1ptt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0014-tenant/tkrw-pr712-0075-0014-app/devfile-sample-1ptt@sha256:4f0735704ed3e1a49700b787b10372102b63533725d1588e45fc4fa9e204c7b5
        name: my-nodejs
        resources: {}
status: {}
